### ISSUE TITLE
custom  max_seq_length

### ISSUE THREAD

**Issue by rmrmg** [rxn4chemistry/rxn_yields#8]
Hello I foolow example from https://github.com/rxn4chemistry/rxn_yields/blob/master/nbs/05_model_training.ipynb with my own data.
It works fine with standard settings but when I changed  "max_seq_length" to higher value (I have reaction longer than 300 characters) it crash with error presented below. I guess the problem is with rxnfp/bert and I need to retrain "models/transformers/bert_pretrained". 
Could you please point me how what should I do? I could found relevant docs.

```
/pytorch/aten/src/THC/THCTensorIndex.cu:272: indexSelectLargeIndex: block: [7,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:272: indexSelectLargeIndex: block: [7,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.                                      
/pytorch/aten/src/THC/THCTensorIndex.cu:272: indexSelectLargeIndex: block: [7,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed. 
[...]
Traceback (most recent call last):  `                                                                                                                                                         
File "./train_suzuka.py", line 46, in <module>                                                                                                                                             
    yield_bert.train_model(train_df, output_dir=args.out, eval_df=test_df)                                                                                                                   
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 289, in train_model                                  
    **kwargs,                                                                                                                                                                                
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 405, in train                                        
    outputs = model(**inputs)                                                                                                                                                                
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__                                                                    
    result = self.forward(*input, **kwargs)                                                                                                                                                   
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/simpletransformers/classification/transformer_models/bert_model.py", line 62, in forward                               
    head_mask=head_mask,                                                                                                                                                                      
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__                                                                    
    result = self.forward(*input, **kwargs)                                                                                                                                                  
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/transformers/modeling_bert.py", line 727, in forward                                                                  
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds                                                                               
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__                                                                    
    result = self.forward(*input, **kwargs)                                                                                                                                                   
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/transformers/modeling_bert.py", line 176, in forward                                                                   
    token_type_embeddings = self.token_type_embeddings(token_type_ids)                                                                                
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__                             
    result = self.forward(*input, **kwargs)                                                                                                           
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward                                   
    self.norm_type, self.scale_grad_by_freq, self.sparse)                                                                                             
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in embedding                               
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)                                                                    
RuntimeError: CUDA error: device-side assert triggered
```

Relevant fragment of my core is here below:
```
model_args = {'num_train_epochs': 15, 'overwrite_output_dir': True,
    'learning_rate': 0.00009659, 'gradient_accumulation_steps': 1,
    'regression': True, "num_labels":1, "fp16": False,
    "evaluate_during_training": False, 'manual_seed': 42,
    "max_seq_length": 850, "train_batch_size": 16,"warmup_ratio": 0.00,
    "config" : { 'hidden_dropout_prob': 0.7987 }
}

model_path =  pkg_resources.resource_filename(
                "rxnfp",
                f"models/transformers/bert_pretrained" # change pretrained to ft to start from the other base model
)

yield_bert = SmilesClassificationModel("bert", model_path, num_labels=1, 
                                       args=model_args, use_cuda=torch.cuda.is_available())
dftrain = pandas.read_csv(args.train, delimiter='\t')
dftest = pandas.read_csv(args.test, delimiter='\t')
train_df = dftrain.iloc[:][['rxn', 'y']] 
test_df = dftest.iloc[:][['rxn', 'y']] #

train_df.columns = ['text', 'labels']
test_df.columns = ['text', 'labels']
mean = train_df.labels.mean()
std = train_df.labels.std()
train_df['labels'] = (train_df['labels'] - mean) / std
test_df['labels'] = (test_df['labels'] - mean) / std
train_df.head()

yield_bert.train_model(train_df, output_dir=args.out, eval_df=test_df)
```

**Comment by rmrmg** [comment]
This is what I did please let me know if it is correct:
1. I download and retrain rxnfp using [example 8 from the repo](https://github.com/rxn4chemistry/rxnfp/blob/master/nbs/08_training_smiles_language_model_from_scratch.ipynb). I onl changed `'max_seq_length': 256,` to `'max_seq_length': 1024`
2. then I copy whole outputs/best_model/ directory to rxn_yield and adjust `model_path` in the script presented in first msg
3. unfortunately it does not work and crash with two problems:
a) chunk size in pool.imap was -1. Variable args["multiprocessing_chunksize"]  in the file simpletransformers/classification/classification_utils.py in line 389 was -1 so I changed:
`p.imap(convert_example_to_feature, examples, chunksize=args["multiprocessing_chunksize"]),   `
`p.imap(convert_example_to_feature, examples, chunksize=100),   `
and this problem was bypassed but another one appears
b) wandb.init 
````Traceback (most recent call last):                                                                                                                                                           
  File "./train_suzuka_max1024prebert.py", line 50, in <module>                                                                                                                              
    yield_bert.train_model(train_df, output_dir=args.out, eval_df=test_df)
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 290, in train_model                                  
    **kwargs,
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 392, in train                                        
    wandb.watch(self.model)
  File "/home/rmrmg/miniconda3/envs/yields/lib/python3.6/site-packages/wandb/__init__.py", line 136, in watch                                                                                
    "You must call `wandb.init` before calling watch")                                                                                                                                       
ValueError: You must call `wandb.init` before calling watch
````
I had no idea hot to fix this so I decided to changed `config.json` and make it as similar as possible to original one (bert_pretrained/config.json)

4. My new config.json is
````{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 256,
  "initializer_range": 0.02,
  "intermediate_size": 512,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 1024,
  "num_attention_heads": 4,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 599,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "use_bfloat16": false,
  "torchscript": false
}
````

and now it works I am able to perform training.
@pschwllr could please you comment on this? Is above described approach corrected?

**Comment by pschwllr** [comment]
Glad you made it work! Yes, it makes sense to change the `max_position_embeddings` to the max length that you want. 

The error that you've posted is related to `wandb`. It can be set up like that:
https://docs.wandb.ai/quickstart#1.-set-up-wandb

**Comment by rmrmg** [comment]
Ths for answer, `max_position_embeddings` is the only change in rxnfp but when I moved model to rxn_yield a made following changes compare to original config from rxnfp.
```
--- bert-best-1024/config.json  2021-12-21 03:40:08.821326088 -0500
+++ bert-best-1024/config.json_oryg     2021-12-20 14:42:16.639450754 -0500

+  "architectures": [
+    "BertForMaskedLM"
+  ],
+  "classifier_dropout": null,
+  "model_type": "bert",
+  "pad_token_id": 0,
+  "position_embedding_type": "absolute",
+  "torch_dtype": "float32",
+  "transformers_version": "4.14.1",
-  "output_attentions": false,
-  "output_hidden_states": false,
-  "output_past": true,
-  "pruned_heads": {},
-  "use_bfloat16": false,
-  "torchscript": false
+  "use_cache": true,
````
Is it ok?

**Comment by pschwllr** [comment]
Looks like you are using a newer transformers version, compared to what we had used when we published the work. Just by looking at it, I think it is ok.

**Comment by pschwllr** [comment]
Closing this issue for now. Feel free to reopen if more related issues occur.
